 #*******************INICIO DEL CÓDIGO AUTO GENERADO ****************************

esphome:
  name: porton-garaje
  friendly_name: Portón Garaje

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key:  "[*****REEMPLAZAR CON SU PROPIO API KEY*****]" 

ota:
  password: "[*****REEMPLAZAR CON SU PROPIA CONTRASEÑA*****]"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Porton-Garaje Fallback Hotspot"
    password: "[*****REEMPLAZAR CON SU PROPIA CONTRASEÑA*****]"

captive_portal:

 #*******************FIN DEL CÓDIGO AUTO GENERADO ******************************

binary_sensor:

- platform: gpio
  pin:
    number: GPIO16
    mode: INPUT_PULLDOWN
    inverted: true
  name: "Garage Door Sensor"
  id: garage_door_contact
  device_class: garage_door
  filters:
    - delayed_on: 30ms


switch:
- platform: gpio
  id: relay1
  pin:
    number: GPIO5
    inverted: False
  restore_mode: ALWAYS_OFF

cover:
  - platform: template
    name: Garage Door
    device_class: garage
    lambda: !lambda |-
      if (id(garage_door_contact).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: relay1
      - delay: 1s
      - switch.turn_off: relay1
    close_action:
      - switch.turn_on: relay1
      - delay: 1s
      - switch.turn_off: relay1
